version: '3'

services: 
  
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - "mongodata:/data/db"
  
  mongo-express:
    image: mongo-express
    container_name: mongo_admin
    restart: always
    ports: 
      - 8081:8081
    depends_on: 
      - mongo  
  
  testapi:
    build: .
    image: testapi:latest
    restart: always
    container_name: testapi
    ports:
      - 5000:80
    environment: 
      MongoDatabaseSettings__Host: mongo
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on: 
      - mongo

volumes: 
  mongodata: